// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHbW8s_vb9iDh5vVXJRpfO1RX-7bPohLg',
    appId: '1:293736296065:web:5be2ac7eb7718ce59e6780',
    messagingSenderId: '293736296065',
    projectId: 'icmc-dorm',
    authDomain: 'icmc-dorm.firebaseapp.com',
    storageBucket: 'icmc-dorm.firebasestorage.app',
    measurementId: 'G-DJZ1YG5H27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwDZw5jjMeQIg5l35W_R4z810r4kggoFE',
    appId: '1:293736296065:android:31cf8ff2e559efe49e6780',
    messagingSenderId: '293736296065',
    projectId: 'icmc-dorm',
    storageBucket: 'icmc-dorm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5LUWzHwMxE9nDPxpxvDcXq8ZR7TknaE',
    appId: '1:293736296065:ios:3db658ae25f6665b9e6780',
    messagingSenderId: '293736296065',
    projectId: 'icmc-dorm',
    storageBucket: 'icmc-dorm.firebasestorage.app',
    iosBundleId: 'com.example.icmcDorm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV5LUWzHwMxE9nDPxpxvDcXq8ZR7TknaE',
    appId: '1:293736296065:ios:3db658ae25f6665b9e6780',
    messagingSenderId: '293736296065',
    projectId: 'icmc-dorm',
    storageBucket: 'icmc-dorm.firebasestorage.app',
    iosBundleId: 'com.example.icmcDorm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHbW8s_vb9iDh5vVXJRpfO1RX-7bPohLg',
    appId: '1:293736296065:web:ac50697d3000d8d89e6780',
    messagingSenderId: '293736296065',
    projectId: 'icmc-dorm',
    authDomain: 'icmc-dorm.firebaseapp.com',
    storageBucket: 'icmc-dorm.firebasestorage.app',
    measurementId: 'G-T4GTQ2ND4J',
  );
}
